/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pemilihandokter;

/**
 *
 * @author Rokerecekecek
 */
public class form1 extends javax.swing.JFrame {

    /**
     * Creates new form form1
     */
    public form1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtalamat = new javax.swing.JTextField();
        jtxtnama = new javax.swing.JTextField();
        jtxtjenis = new javax.swing.JTextField();
        jtxtusia = new javax.swing.JTextField();
        jtxtgol = new javax.swing.JTextField();
        jtxtstatus = new javax.swing.JTextField();
        jtxtkewar = new javax.swing.JTextField();
        jtxtwaktu = new javax.swing.JTextField();
        jtxtspesial = new javax.swing.JTextField();
        jconadokt = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Pilih Dokter");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 40, 70, 20);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 70, 130, 30);

        jLabel3.setText("Alamat");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 100, 130, 30);

        jLabel4.setText("Usia");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 130, 130, 30);

        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 160, 130, 30);

        jLabel6.setText("Gol dar");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 190, 130, 30);

        jLabel7.setText("Status");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 220, 130, 30);

        jLabel8.setText("Kewarganegaraan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 250, 130, 30);

        jLabel9.setText("Dokter Spesialis");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 310, 130, 30);

        jLabel10.setText("Waktu Praktek");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 280, 130, 30);

        jtxtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtalamatActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtalamat);
        jtxtalamat.setBounds(130, 100, 160, 30);

        jtxtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnamaActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtnama);
        jtxtnama.setBounds(130, 70, 160, 30);
        getContentPane().add(jtxtjenis);
        jtxtjenis.setBounds(130, 160, 160, 30);
        getContentPane().add(jtxtusia);
        jtxtusia.setBounds(130, 130, 160, 30);

        jtxtgol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtgolActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtgol);
        jtxtgol.setBounds(130, 190, 160, 30);
        getContentPane().add(jtxtstatus);
        jtxtstatus.setBounds(130, 220, 160, 30);
        getContentPane().add(jtxtkewar);
        jtxtkewar.setBounds(130, 250, 160, 30);

        jtxtwaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtwaktuActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtwaktu);
        jtxtwaktu.setBounds(130, 280, 160, 30);
        getContentPane().add(jtxtspesial);
        jtxtspesial.setBounds(130, 310, 160, 30);

        jconadokt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Plilih Salah satu--", "DR. Farras Yassar", "DR. Anisa Putri", "DR. Harun Fajar", " " }));
        jconadokt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jconadoktActionPerformed(evt);
            }
        });
        getContentPane().add(jconadokt);
        jconadokt.setBounds(130, 40, 160, 20);

        jLabel11.setText("PEMILIHAN DOKTER");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(130, 10, 120, 20);

        setBounds(0, 0, 395, 414);
    }// </editor-fold>//GEN-END:initComponents

    private void jconadoktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jconadoktActionPerformed
       if(jconadokt.getSelectedItem().equals("DR. Farras Yassar")){
jtxtnama.setText("DR. Farras Yassar ");
jtxtalamat.setText("Jl. Surabaya 16, Malang");
jtxtusia.setText("20 Tahun");
jtxtjenis.setText("Laki-Laki");
jtxtgol.setText("A");
jtxtstatus.setText("Belum Menikah ");
jtxtkewar.setText("Indonesia");
jtxtspesial.setText("Dokter Umum");
jtxtwaktu.setText(" Pagi (07.00-15.00)");
}
else
if(jconadokt.getSelectedItem().equals("DR. Anisa Putri")){
jtxtnama.setText("DR. Anisa Putri");
jtxtalamat.setText("Jl. Veteran 3, Malang");
jtxtusia.setText("20 Tahun");
jtxtjenis.setText("Perempuan");
jtxtgol.setText("O");
jtxtstatus.setText("Belum Menikah");
jtxtkewar.setText("Indonesia");
jtxtspesial.setText("Dokter Gigi");
jtxtwaktu.setText(" Sore (16.00-22.00)");
}
else
if(jconadokt.getSelectedItem().equals("DR. Harun Fajar")){
jtxtnama.setText("DR. Harun Fajar ");
jtxtalamat.setText("Jl. Bandung 9, Malang");
jtxtusia.setText("20 Tahun");
jtxtjenis.setText("Laki-Laki");
jtxtgol.setText("B");
jtxtstatus.setText("Belum Menikah");
jtxtkewar.setText("Indonesia");
jtxtspesial.setText("Dokter Gizi");
jtxtwaktu.setText(" Malam (22.00-06.00)");
}
    
    }//GEN-LAST:event_jconadoktActionPerformed

    private void jtxtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnamaActionPerformed

    private void jtxtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtalamatActionPerformed

    private void jtxtgolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtgolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtgolActionPerformed

    private void jtxtwaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtwaktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtwaktuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jconadokt;
    private javax.swing.JTextField jtxtalamat;
    private javax.swing.JTextField jtxtgol;
    private javax.swing.JTextField jtxtjenis;
    private javax.swing.JTextField jtxtkewar;
    private javax.swing.JTextField jtxtnama;
    private javax.swing.JTextField jtxtspesial;
    private javax.swing.JTextField jtxtstatus;
    private javax.swing.JTextField jtxtusia;
    private javax.swing.JTextField jtxtwaktu;
    // End of variables declaration//GEN-END:variables
}
